name = "IntroductionJulia"
uuid = "2030fae2-b74c-49bd-863b-12c72d19aee6"
authors = ["RobinChaussemy <chaussemy.robin@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
